esphome:
  name: rounded-lcd
  friendly_name: "Dummy-13 head"

packages:
  device: !include device.yaml
  homeassistant: !include api.yaml
  hardware: !include hardware.yaml
  sensors: !include sensors.yaml
  graphics: !include resources/lvgl.yaml

globals:
    - id: remain_time_data
      type: std::string
      initial_value: '"--:--"'
    - id: current_page
      type: int
      restore_value: no
      initial_value: '0'
    - id: co2_concentration_str
      type: std::string
      initial_value: '"-- ppm"'
    - id: pm25_value_str
      type: std::string
      initial_value: '"-- µg/m³"'
      
interval:
  - interval: 10s
    then:
      - script.execute: switch_page
      
# Шрифт для текста
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 30
  - file: "gfonts://Roboto"
    id: font_remain
    size: 43
  - file: "gfonts://Roboto"
    id: font_main_clock
    size: 80
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kyiv
    on_time:
      - cron: '* * * * * *'
        then:
          - script.execute: time_update



script:
  - id: switch_page
    then:
      - lambda: |-
          id(current_page)++;
          if (id(current_page) > 1) {
            id(current_page) = 0;
          }

        # if (id(current_page) == 0) {
        #   id(printer_page).show();
        # } else if (id(current_page) == 1) {
        #   id(clock_page).show();
        # }
      - if:
          condition:
            lambda: 'return id(current_page) == 0;'
          then:
            - lvgl.page.show: printer_page
      - if:
          condition:
            lambda: 'return id(current_page) == 1;'
          then:
            - lvgl.page.show: clock_page

  - id: time_update
    then:
      - lvgl.label.update:
          id: main_time_label
          text: !lambda |-
            char buff[10] = "-";
            auto time = id(sntp_time).now();
            if (time.is_valid())              
              sprintf(buff, "%02d:%02d", time.hour, time.minute);
            return buff;
      - lvgl.label.update:
          id: time_label
          text: !lambda |-
            char buff[10] = "-";
            auto time = id(sntp_time).now();
            if (time.is_valid())              
              sprintf(buff, "%02d:%02d", time.hour, time.minute);
            return buff;
    

    
