esphome:
  name: rounded-lcd
  friendly_name: "Dummy-13 head"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  encryption:
    key: "HfSHrywlFiF/SuLxtWt6UeGOwvcnnYipdd0nidyih4A="
    
ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "HUAWEI-V5ZNS6"
  password: "134679852"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dummy-13 head Fallback Hotspot"
    password: "134679852"

captive_portal:
    
# SPI-шина
spi:
  clk_pin: GPIO2      # SCK
  mosi_pin: GPIO3     # MOSI (SDA на дисплее)
  # miso не нужен
  
# --- I²C шина ---
i2c:
  sda: GPIO7
  scl: GPIO6
  scan: true
  frequency: 100kHz
#  id: bus_a

# --- Датчики ---
sensor:
  # A103 (AHT20 + BMP280)
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Температура (AHT20)"
      id: temp_aht20
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      icon: mdi:thermometer
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    humidity:
      name: "Вологість (AHT20)"
      id: hum_aht20
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
    address: 0x38
    update_interval: 60s
  - platform: bmp280_i2c
    pressure:
      name: "Атмосферний тиск (BME280)"
      id: pressure_bmp280
      device_class: atmospheric_pressure
      state_class: measurement
      unit_of_measurement: "мм.рт.ст."
      icon: mdi:gauge
      accuracy_decimals: 0
      filters:
        - multiply: 0.75006
        - round: 0
    temperature:
      name: "Temperature (BME280)"
      id: temp_bmp280
      oversampling: 16x
      accuracy_decimals: 0
    address: 0x77
    update_interval: 60s
    
  # ENS160 (качество воздуха)
  - platform: ens160_i2c
    eco2:
      name: "Еквівалентний CO₂ (ENS160)"
      device_class: carbon_dioxide
      state_class: measurement
      unit_of_measurement: "ppm"
      icon: mdi:molecule-co2
    tvoc:
      name: "TVOC (ENS160)"
      id: tvoc
      state_class: measurement
      unit_of_measurement: "µg/m³"
      icon: mdi:chemical-weapon
    aqi:
      name: "AQI (ENS160)"
      state_class: measurement
      icon: mdi:weather-hazy
    compensation:
      temperature: temp_aht20
      humidity: hum_aht20
    address: 0x53
    update_interval: 60s
  
# Дисплей
display:
  - platform: ili9xxx
    model: GC9A01A
    cs_pin: GPIO5
    dc_pin: GPIO0
    reset_pin: GPIO1
    color_palette: 8BIT
    dimensions: 240x240
    rotation: 0
    invert_colors: true
    data_rate: 20MHz
    id: round_display

globals:
    - id: remain_time_data
      type: std::string
      initial_value: '"--:--"'
    - id: current_page
      type: int
      restore_value: no
      initial_value: '0'
    - id: co2_concentration_str
      type: std::string
      initial_value: '"-- ppm"'
    - id: pm25_value_str
      type: std::string
      initial_value: '"-- µg/m³"'
lvgl:
  pages:
    - id: printer_page
      widgets:
      - obj:
          id: printer_page_bg
          bg_color: 0x000000
          bg_opa: 100%
          width: 240
          height: 240
          align: CENTER
          border_width: 0
          
      - arc:
          id: progress_bar
          width: 236
          height: 236
          align: TOP_LEFT
          translate_x: 2
          translate_y: 2
          value: 50
          
          # MAIN (фон дуги)
          arc_color: 0x367A69
          arc_opa: 100%
          arc_width: 14

          # INDICATOR (активная часть дуги)
          indicator:
            arc_color: 0x97D5C6
            arc_opa: 100%
            arc_width: 14

          # KNOB (ползунок — прозрачный)
          knob:
            bg_opa: 0%
      
      # progress
      - label:
          id: progress_label
          text: "100 %"
          height: 50
          translate_x: 0
          translate_y: 30
          align: TOP_MID
          text_color: 0x97D5C6
          text_opa: 100%
          text_font: font_remain

      # remain time
      - label:
          id: time_remain_label
          text: "--:--"
          height: 50
          translate_x: 0
          translate_y: 80
          align: TOP_MID
          text_color: 0xDBF9FF
          text_opa: 100%
          text_font: font_remain

      # now time
      - label:
          id: time_label
          text: "--:--"
          height: 50
          translate_x: 0
          translate_y: 181
          align: TOP_MID
          text_color: 0xDBF9FF
          text_opa: 100%
          text_font: font_small
    
    - id: clock_page
      widgets:
        - obj:  
            id: clock_page_bg
            bg_color: 0x000000
            bg_opa: 100%
            width: 240
            height: 240
            align: CENTER
            border_width: 0
        - label:
            id: main_time_label
            text: "--:--"
            translate_x: 0
            translate_y: 46
            align: TOP_MID
            text_color: 0xDBF9FF
            text_opa: 100%
            text_font: font_main_clock 


# Шрифт для текста
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 30
  - file: "gfonts://Roboto"
    id: font_remain
    size: 43
  - file: "gfonts://Roboto"
    id: font_main_clock
    size: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kyiv
    on_time:
      - cron: '* * * * * *'
        then:
          - script.execute: time_update

interval:
  - interval: 10s
    then:
      - script.execute: switch_page

script:
  - id: switch_page
    then:
      - lambda: |-
          id(current_page)++;
          if (id(current_page) > 1) {
            id(current_page) = 0;
          }

        # if (id(current_page) == 0) {
        #   id(printer_page).show();
        # } else if (id(current_page) == 1) {
        #   id(clock_page).show();
        # }
      - if:
          condition:
            lambda: 'return id(current_page) == 0;'
          then:
            - lvgl.page.show: printer_page
      - if:
          condition:
            lambda: 'return id(current_page) == 1;'
          then:
            - lvgl.page.show: clock_page

  - id: time_update
    then:
      - lvgl.label.update:
          id: main_time_label
          text: !lambda |-
            char buff[10] = "-";
            auto time = id(sntp_time).now();
            if (time.is_valid())              
              sprintf(buff, "%02d:%02d", time.hour, time.minute);
            return buff;
      - lvgl.label.update:
          id: time_label
          text: !lambda |-
            char buff[10] = "-";
            auto time = id(sntp_time).now();
            if (time.is_valid())              
              sprintf(buff, "%02d:%02d", time.hour, time.minute);
            return buff;
    
text_sensor:
    - platform: homeassistant
      id: CO2_concentration
      entity_id: sensor.air_quality_station_co_concentration
      on_value:
        then:
          - lambda: |-
             auto str = x;
             id(co2_concentration_str) = str;
#          - lvgl.label.update:
#                id: time_remain_label
#                text:
#                  format: "%s"
#                  args: [ id(remain_time_data).c_str() ]
    - platform: homeassistant
      id: pm25_value
      entity_id: sensor.air_quality_station_pm2_5
      on_value:
        then:
          - lambda: |-
             auto str = x;
             id(pm25_value_str) = str;
#          - lvgl.label.update:
#                id: time_remain_label
#                text:
#                  format: "%s"
#                  args: [ id(remain_time_data).c_str() ]
    - platform: homeassistant
      id: time_remain
      entity_id: sensor.octoprint_end_time
      attribute: remaining_text
      on_value:
        then:
          - lambda: |-
             auto str = x;
             id(remain_time_data) = str;
          - lvgl.label.update:
                id: time_remain_label
                text:
                  format: "%s"
                  args: [ id(remain_time_data).c_str() ]
    
